name: Cookier

on: push
  # schedule:
  #   - cron: "0 */6 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twikit==1.7.6

      - name: Run scraping script
        env:  # As variáveis de ambiente devem ser passadas aqui, fora do bloco "run"
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        run: |
          python get_cookie.py

      - name: Upload cookies artifact
        uses: actions/upload-artifact@v3
        with:
          name: cookies
          path: cookies.json
