name: Scrape Twitter

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Use a versão 3.11 do Python

      - name: Install dependencies
        run: |
          pip install snscrape pandas

      - name: Run scraping script
        run: |
          python scrape_twitter.py

      - name: Upload Tweets CSV
        uses: actions/upload-artifact@v3
        with:
          name: scraped-tweets
          path: tweets_vacina_hpv_*.csv
