name: Twikiter

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */6 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snscrape

      - name: Run scraping script
        env:  # As variáveis de ambiente devem ser passadas aqui, fora do bloco "run"
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        run: |
          python sns_scraper.py
